# Generated by Django 4.2.2 on 2023-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('accounts', '0003_alter_petstagramuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstagramuser',
            name='likes',
            field=models.ManyToManyField(to='common.like'),
        ),
    ]
