# Generated by Django 4.2.2 on 2023-07-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('accounts', '0005_alter_petstagramuser_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstagramuser',
            name='likes',
            field=models.ManyToManyField(related_name='users', to='common.like'),
        ),
    ]
